/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.im.expensems.view;

import com.im.expensems.controler.CategoryDAOImp;
import com.im.expensems.model.Category;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rpa29
 */
public class MainInternalFrame extends javax.swing.JInternalFrame {

    
    //Creating the initial requirements
    GridBagLayout gbl = new GridBagLayout();
    CategoryManager catManager;
    ExpenceManager exManager;
        
    
    public MainInternalFrame() {
        initComponents();
        catManager = new CategoryManager();
        exManager = new ExpenceManager();
        
        DynamicPanel.setLayout(gbl);
        
        //Add catagory manager to dynamic panel
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        DynamicPanel.add(catManager);
         
        //Add Expence manager to dynamic panel
        gbc.gridx = 0;
        gbc.gridy = 0;
        DynamicPanel.add(exManager);    
        
        catManager.setVisible(true);
        exManager.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staticPanel = new javax.swing.JPanel();
        btnCategory = new javax.swing.JButton();
        btnExpence = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Menu");

        staticPanel.setBackground(new java.awt.Color(255, 204, 204));
        staticPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        btnCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCategory.setText("Category");
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });

        btnExpence.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExpence.setText("Expence");
        btnExpence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpenceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout staticPanelLayout = new javax.swing.GroupLayout(staticPanel);
        staticPanel.setLayout(staticPanelLayout);
        staticPanelLayout.setHorizontalGroup(
            staticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staticPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(btnExpence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        staticPanelLayout.setVerticalGroup(
            staticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staticPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExpence, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(380, Short.MAX_VALUE))
        );

        getContentPane().add(staticPanel, java.awt.BorderLayout.LINE_START);

        DynamicPanel.setBackground(new java.awt.Color(204, 204, 255));
        DynamicPanel.setMaximumSize(new java.awt.Dimension(327670, 327670));
        DynamicPanel.setMinimumSize(new java.awt.Dimension(400, 200));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
       //Show category
        catManager.setVisible(true);
        exManager.setVisible(false);
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnExpenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpenceActionPerformed
       //Show Expences
        catManager.setVisible(false);
        exManager.setVisible(true);
       
    }//GEN-LAST:event_btnExpenceActionPerformed
        
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnExpence;
    private javax.swing.JPanel staticPanel;
    // End of variables declaration//GEN-END:variables
}
